apiVersion: apps/v1
kind: Deployment
metadata:
  name: planpal-server
spec:
  replicas: 2 # ì• í”Œë¦¬ì¼€ì´ì…˜ì„ ëª‡ ê°œì˜ Podë¡œ ì‹¤í–‰í• ì§€ ì§€ì •
  selector:
    matchLabels:
      app: planpal-server
  template:
    metadata:
      labels:
        app: planpal-server
    spec:
      containers:
        - name: planpal-server-container
          image: asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-server/planpal-remote
          ports:
            - containerPort: 8080
          # ğŸ”¹ ì‹œí¬ë¦¿ì„ íŒŒì¼ë¡œ ë§ˆìš´íŠ¸
          volumeMounts:
            - name: secret-volume
              mountPath: "/app/resources"
              readOnly: true
            - name: ai-key-volume
              mountPath: "/app/keys"
              readOnly: true
      # ğŸ”¹ ì¿ ë²„ë„¤í‹°ìŠ¤ Secretì„ Volumeìœ¼ë¡œ ì •ì˜
      volumes:
        - name: secret-volume
          secret:
            secretName: planpal-remote-secret
            items:
              - key: secret.yml
                path: secret.yml
        - name: ai-key-volume
          secret:
            secretName: planpal-ai-secret
            items:
              - key: gemini-ai-key.json
                path: gemini-ai-key.json